databases:
  - name: studentdb
    databaseName: studentdb
    user: studentdb_user
    ipAllowList: [] # empty means all IP addresses are allowed

services:
  - type: web
    name: student-learning-backend
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: DB_HOST
        fromDatabase:
          name: studentdb
          property: host
      - key: DB_PORT
        fromDatabase:
          name: studentdb
          property: port
      - key: DB_NAME
        fromDatabase:
          name: studentdb
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: studentdb
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: studentdb
          property: password
